<?php

return [
    'models' => [
        'llama-3.1-8b-instant' => [
            'name' => 'Llama 3.1 8B',
            'type' => 'production',
            'speed_tps' => 560,
            'input_price_per_1m' => 0.05,
            'output_price_per_1m' => 0.08,
            'rate_limits' => '250K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 131072,
        ],
        'llama-3.3-70b-versatile' => [
            'name' => 'Llama 3.3 70B',
            'type' => 'production',
            'speed_tps' => 280,
            'input_price_per_1m' => 0.59,
            'output_price_per_1m' => 0.79,
            'rate_limits' => '300K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 32768,
        ],
        'meta-llama/llama-guard-4-12b' => [
            'name' => 'Llama Guard 4 12B',
            'type' => 'production',
            'speed_tps' => 1200,
            'input_price_per_1m' => 0.20,
            'output_price_per_1m' => 0.20,
            'rate_limits' => '30K TPM / 100 RPM',
            'context_window' => 131072,
            'max_completion' => 1024,
            'max_file_size' => '20 MB',
        ],
        'openai/gpt-oss-120b' => [
            'name' => 'GPT OSS 120B',
            'type' => 'production',
            'speed_tps' => 500,
            'input_price_per_1m' => 0.15,
            'output_price_per_1m' => 0.60,
            'rate_limits' => '250K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 65536,
        ],
        'openai/gpt-oss-20b' => [
            'name' => 'GPT OSS 20B',
            'type' => 'production',
            'speed_tps' => 1000,
            'input_price_per_1m' => 0.075,
            'output_price_per_1m' => 0.30,
            'rate_limits' => '250K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 65536,
        ],
        'whisper-large-v3' => [
            'name' => 'Whisper Large V3',
            'type' => 'production',
            'input_price_per_1m' => 0.00,
            'output_price_per_1m' => 0.00,
            'pricing_unit' => 'per_hour',
            'pricing_note' => '$0.111 per hour',
            'rate_limits' => '200K ASH / 300 RPM',
            'max_file_size' => '100 MB',
        ],
        'whisper-large-v3-turbo' => [
            'name' => 'Whisper Large V3 Turbo',
            'type' => 'production',
            'input_price_per_1m' => 0.00,
            'output_price_per_1m' => 0.00,
            'pricing_unit' => 'per_hour',
            'pricing_note' => '$0.04 per hour',
            'rate_limits' => '400K ASH / 400 RPM',
        ],
        'groq/compound' => [
            'name' => 'Groq Compound',
            'type' => 'system',
            'speed_tps' => 450,
            'input_price_per_1m' => 0.00,
            'output_price_per_1m' => 0.00,
            'pricing_note' => 'Included in system pricing',
            'rate_limits' => '200K TPM / 200 RPM',
            'context_window' => 131072,
            'max_completion' => 8192,
        ],
        'groq/compound-mini' => [
            'name' => 'Groq Compound Mini',
            'type' => 'system',
            'speed_tps' => 450,
            'input_price_per_1m' => 0.00,
            'output_price_per_1m' => 0.00,
            'pricing_note' => 'Included in system pricing',
            'rate_limits' => '200K TPM / 200 RPM',
            'context_window' => 131072,
            'max_completion' => 8192,
        ],
        'canopylabs/orpheus-arabic-saudi' => [
            'name' => 'Orpheus Arabic Saudi',
            'type' => 'preview',
            'input_price_per_1m' => 40.00,
            'output_price_per_1m' => 0.00,
            'pricing_unit' => 'per_1m_characters',
            'pricing_note' => '$40.00 per 1M characters',
            'rate_limits' => '50K TPM / 250 RPM',
            'context_window' => 4000,
            'max_completion' => 50000,
        ],
        'canopylabs/orpheus-v1-english' => [
            'name' => 'Orpheus V1 English',
            'type' => 'preview',
            'input_price_per_1m' => 22.00,
            'output_price_per_1m' => 0.00,
            'pricing_unit' => 'per_1m_characters',
            'pricing_note' => '$22.00 per 1M characters',
            'rate_limits' => '50K TPM / 250 RPM',
            'context_window' => 4000,
            'max_completion' => 50000,
        ],
        'meta-llama/llama-4-maverick-17b-128e-instruct' => [
            'name' => 'Llama 4 Maverick 17B 128E',
            'type' => 'preview',
            'speed_tps' => 600,
            'input_price_per_1m' => 0.20,
            'output_price_per_1m' => 0.60,
            'rate_limits' => '300K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 8192,
            'max_file_size' => '20 MB',
        ],
        'meta-llama/llama-4-scout-17b-16e-instruct' => [
            'name' => 'Llama 4 Scout 17B 16E',
            'type' => 'preview',
            'speed_tps' => 750,
            'input_price_per_1m' => 0.11,
            'output_price_per_1m' => 0.34,
            'rate_limits' => '300K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 8192,
            'max_file_size' => '20 MB',
        ],
        'meta-llama/llama-prompt-guard-2-22m' => [
            'name' => 'Llama Prompt Guard 2 22M',
            'type' => 'preview',
            'input_price_per_1m' => 0.03,
            'output_price_per_1m' => 0.03,
            'rate_limits' => '30K TPM / 100 RPM',
            'context_window' => 512,
            'max_completion' => 512,
        ],
        'meta-llama/llama-prompt-guard-2-86m' => [
            'name' => 'Llama Prompt Guard 2 86M',
            'type' => 'preview',
            'input_price_per_1m' => 0.04,
            'output_price_per_1m' => 0.04,
            'rate_limits' => '30K TPM / 100 RPM',
            'context_window' => 512,
            'max_completion' => 512,
        ],
        'moonshotai/kimi-k2-instruct-0905' => [
            'name' => 'Kimi K2 0905',
            'type' => 'preview',
            'speed_tps' => 200,
            'input_price_per_1m' => 1.00,
            'output_price_per_1m' => 3.00,
            'rate_limits' => '250K TPM / 1K RPM',
            'context_window' => 262144,
            'max_completion' => 16384,
        ],
        'openai/gpt-oss-safeguard-20b' => [
            'name' => 'Safety GPT OSS 20B',
            'type' => 'preview',
            'speed_tps' => 1000,
            'input_price_per_1m' => 0.075,
            'output_price_per_1m' => 0.30,
            'rate_limits' => '150K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 65536,
        ],
        'qwen/qwen3-32b' => [
            'name' => 'Qwen3-32B',
            'type' => 'preview',
            'speed_tps' => 400,
            'input_price_per_1m' => 0.29,
            'output_price_per_1m' => 0.59,
            'rate_limits' => '300K TPM / 1K RPM',
            'context_window' => 131072,
            'max_completion' => 40960,
        ],
    ],
];
